name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 2,11 * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: auto
        run: |
          git config --local user.email "kottbeatrice0125@hotmail.com"
          git config --local user.name "kottbeatrice0125"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "test 1234"
          git push
